<?php
declare(strict_types=1);

/**
 * AUSUS — public API surface snapshot guardrail.
 *
 * Emits, for every package on the path, the deterministic list of
 * top-level symbols (classes, interfaces, enums) declared in src/.
 * Compares the live emit to a checked-in snapshot. If anything
 * appeared or disappeared without intent, this script exits non-zero
 * and shows the diff.
 *
 * UPDATE the snapshot intentionally with:
 *     UPDATE_SNAPSHOT=1 php apps/playground/api-surface.php
 *
 * See docs/API-GOVERNANCE.md and docs/SEMVER-CONTRACT.md.
 */

$repoRoot = dirname(__DIR__, 2);
$snapshotFile = $repoRoot . '/apps/playground/api-surface.snapshot.txt';

$packages = [
    'kernel'           => 'packages/kernel/src',
    'persistence-sql'  => 'packages/persistence-sql/src',
    'runtime-default'  => 'packages/runtime-default/src',
    'api-http'         => 'packages/api-http/src',
    'starter'          => 'packages/starter/src',
];

$emitted = [];
$emitted[] = "# AUSUS API surface snapshot — regenerated by apps/playground/api-surface.php";
$emitted[] = "# Each line: <package> <kind> <FQN> [@internal] [@experimental]";
$emitted[] = "";

foreach ($packages as $pkg => $rel) {
    foreach (glob("$repoRoot/$rel/*.php") as $file) {
        $source = file_get_contents($file);
        // detect file namespace
        $ns = null;
        if (preg_match('/^\s*namespace\s+([^;]+)\s*;/m', $source, $m)) {
            $ns = trim($m[1]);
        }
        // detect every top-level class/interface/enum
        $pattern = '/^\s*(?:final\s+|abstract\s+)?(?:readonly\s+)?(class|interface|enum)\s+([A-Za-z_][A-Za-z0-9_]*)/m';
        if (preg_match_all($pattern, $source, $matches, PREG_SET_ORDER)) {
            foreach ($matches as $mm) {
                [$line, $kind, $name] = $mm;
                $fqn = $ns ? "$ns\\$name" : $name;

                // Look up the preceding docblock to detect @internal / @experimental tags
                $declPos = strpos($source, $line);
                $tags = [];
                if ($declPos !== false) {
                    $upToDecl = substr($source, 0, $declPos);
                    // The closest doc-block above the declaration
                    if (preg_match('#/\*\*(.*?)\*/\s*$#s', $upToDecl, $dm)) {
                        $dc = $dm[1];
                        if (stripos($dc, '@internal') !== false) $tags[] = '@internal';
                        if (stripos($dc, '@experimental') !== false) $tags[] = '@experimental';
                    }
                }
                $emitted[] = sprintf("%-16s %-9s %s%s",
                    $pkg, $kind, $fqn,
                    $tags ? '   ' . implode(' ', $tags) : '');
            }
        }
    }
}

$emitted[] = "";
$payload = implode("\n", $emitted) . "\n";

if (getenv('UPDATE_SNAPSHOT') === '1') {
    file_put_contents($snapshotFile, $payload);
    echo "[api-surface] wrote snapshot ($snapshotFile)\n";
    echo $payload;
    exit(0);
}

if (!file_exists($snapshotFile)) {
    fwrite(STDERR, "[api-surface] no snapshot at $snapshotFile — run with UPDATE_SNAPSHOT=1 to create one.\n");
    exit(2);
}

$existing = file_get_contents($snapshotFile);
if ($existing === $payload) {
    echo "[api-surface] ✓ public surface matches snapshot\n";
    exit(0);
}

// Diff
echo "[api-surface] ✗ public surface drift detected.\n\n";
$expectedLines = explode("\n", $existing);
$actualLines = explode("\n", $payload);

$missing = array_diff($expectedLines, $actualLines);
$added   = array_diff($actualLines, $expectedLines);

if ($missing) {
    echo "  REMOVED (or renamed) symbols:\n";
    foreach ($missing as $l) if (trim($l) !== '') echo "    - $l\n";
}
if ($added) {
    echo "\n  ADDED (new accidentally-public symbols?) :\n";
    foreach ($added as $l) if (trim($l) !== '') echo "    + $l\n";
}
echo "\nIf this is intentional, re-run with UPDATE_SNAPSHOT=1 and commit the new snapshot.\n";
echo "Otherwise, tag the new symbol @internal or revert the rename.\n";
exit(1);
